version: 0.2.1
name: grafana
displayName: grafana
createdAt: "2024-10-14T10:25:26Z"
description: '`grafana` is the grafana spec definition'
links:
- name: KCL homepage
  url: https://kcl-lang.io/
- name: KCL repo
  url: https://github.com/kcl-lang/kcl
install: |
  #### Add `grafana` with tag `0.2.1` as dependency
  ```
  kcl mod add grafana:0.2.1
  ```

  #### Pull `grafana` with tag `0.2.1` to local
  ```
  kcl mod pull grafana:0.2.1
  ```
maintainers:
- name: kcl-lang.io
  email: kcl-lang.io@domainsbyproxy.com
provider:
  name: kcl-lang.io
