name: Check KCL Modules Checksum

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_modules_checksum:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Get dependencies
        run: go get -v ./...

      - name: Run checksum tool
        run: go run ./checksum-tool/main.go

      - name: Upload Checksum Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: checksum-report
          path: ./checksum-report.md
